/**
 * =====================================================================
 *  アンケート項目の定義
 * ---------------------------------------------------------------------
 *  質問の追加・変更・並び替えはこのファイルで行えます。
 *  id は src/types/survey.ts の SurveyAnswers のキーと一致させてください。
 * =====================================================================
 */

import type { SurveyStep, SurveyAnswers } from '../types/survey'
import { PREFECTURES } from '../data/prefectures'

/** 試験導入の連絡先を表示する回答値（この値のときだけ連絡先フォームを表示） */
export const TRIAL_INTEREST_WITH_CONTACT = [
  '無料試験導入に興味がある',
  'デモを見てみたい',
  '詳しい説明を聞きたい',
]

export const SURVEY_STEPS: SurveyStep[] = [
  {
    id: 'about-you',
    title: '回答者について',
    description: 'まずはあなたのことを教えてください。',
    questions: [
      {
        id: 'respondent_role',
        label: 'あなたの立場を教えてください',
        kind: 'single',
        required: true,
        options: [
          '一般生徒',
          '生徒会',
          '文化祭実行委員',
          '部活動・出店担当者',
          '教職員',
          'その他',
        ],
      },
      {
        id: 'prefecture',
        label: 'お住まい・学校がある都道府県',
        kind: 'prefecture',
        required: true,
        options: [...PREFECTURES],
      },
      {
        id: 'school_type',
        label: '学校の種類',
        kind: 'single',
        required: true,
        options: [
          '公立高校',
          '私立高校',
          '通信制高校',
          '中高一貫校',
          '高等専門学校',
          '中学校',
          'その他',
        ],
      },
      {
        id: 'school_name',
        label: '学校名（任意）',
        note: '学校名は集計と試験導入の相談以外には使用しません。',
        kind: 'text',
        required: false,
        maxLength: 60,
        placeholder: '例）〇〇高等学校',
      },
    ],
  },
  {
    id: 'current-operation',
    title: '現在の文化祭運営',
    description: 'いまの文化祭の運営や情報発信について教えてください。',
    questions: [
      {
        id: 'current_information_methods',
        label: '文化祭情報をどのように発信していますか',
        note: '当てはまるものをすべて選んでください。',
        kind: 'multi',
        required: true,
        options: [
          '紙のパンフレット',
          '学校公式サイト',
          '文化祭専用サイト',
          'Instagram',
          'X',
          'LINE',
          '校内掲示',
          'Googleフォーム・Googleサイト',
          '特に発信していない',
          'その他',
        ],
      },
      {
        id: 'update_availability',
        label: '文化祭の出店情報やスケジュールは、当日に更新できますか',
        kind: 'single',
        required: true,
        options: [
          '簡単に更新できる',
          '一部のみ更新できる',
          '更新が難しい',
          '更新できない',
          '分からない',
        ],
      },
      {
        id: 'emergency_communication_methods',
        label: '急な変更や中止を、来場者にどのように伝えていますか',
        note: '当てはまるものをすべて選んでください。',
        kind: 'multi',
        required: true,
        options: [
          '校内アナウンス',
          '校内掲示の貼り替え',
          'SNSで発信',
          'LINEなどで連絡',
          '実行委員が口頭で伝える',
          '特に手段がない',
          'その他',
        ],
      },
      {
        id: 'congestion_experience',
        label: '文化祭当日に混雑や長い待ち時間が問題になったことはありますか',
        kind: 'single',
        required: true,
        options: ['よくある', 'ときどきある', 'あまりない', 'ない', '分からない'],
      },
    ],
  },
  {
    id: 'problems',
    title: '困っていること',
    description: '文化祭の準備・運営で大変なことを教えてください。',
    questions: [
      {
        id: 'operational_problems',
        label: '文化祭準備や当日運営で大変だと思うこと',
        note: '当てはまるものをすべて選んでください。',
        kind: 'multi',
        required: true,
        options: [
          '出店情報の収集',
          '紙のパンフレット作成',
          '出店場所の案内',
          'スケジュール管理',
          '情報の変更・修正',
          '混雑への対応',
          '来場者へのお知らせ',
          '実行委員間の情報共有',
          '先生との確認',
          '前年度からの引き継ぎ',
          '売上や来場者数の集計',
          '特にない',
          'その他',
        ],
      },
      {
        id: 'biggest_problem',
        label: '最も解決したい課題',
        note: '1つだけ選んでください。',
        kind: 'single',
        required: true,
        options: [
          '出店情報の収集',
          '紙のパンフレット作成',
          '出店場所の案内',
          'スケジュール管理',
          '情報の変更・修正',
          '混雑への対応',
          '来場者へのお知らせ',
          '実行委員間の情報共有',
          '先生との確認',
          '前年度からの引き継ぎ',
          '売上や来場者数の集計',
          '特にない',
        ],
      },
      {
        id: 'problem_details',
        label: '具体的に困った経験があれば教えてください（任意）',
        kind: 'textarea',
        required: false,
        maxLength: 500,
        placeholder: '例）当日に出店場所が変わったが、来場者にうまく伝えられなかった。',
      },
    ],
  },
  {
    id: 'features',
    title: '欲しい機能',
    description: 'あったら便利だと思う機能を教えてください。',
    questions: [
      {
        id: 'desired_features',
        label: '便利だと思う機能',
        note: '当てはまるものをすべて選んでください。',
        kind: 'multi',
        required: true,
        options: [
          '出店一覧',
          'カテゴリ検索',
          'デジタル校内マップ',
          'リアルタイム混雑表示',
          'お知らせの即時配信',
          '整理券・順番待ち',
          'スケジュール表示',
          'スタンプラリー',
          '投票・人気ランキング',
          '落とし物情報',
          '管理画面',
          '売上管理',
          '来場データ分析',
          '翌年度へのデータ引き継ぎ',
          '多言語対応',
          'その他',
        ],
      },
      {
        id: 'most_desired_feature',
        label: '最も使いたい機能',
        note: '1つだけ選んでください。',
        kind: 'single',
        required: true,
        options: [
          '出店一覧',
          'カテゴリ検索',
          'デジタル校内マップ',
          'リアルタイム混雑表示',
          'お知らせの即時配信',
          '整理券・順番待ち',
          'スケジュール表示',
          'スタンプラリー',
          '投票・人気ランキング',
          '落とし物情報',
          '管理画面',
          '売上管理',
          '来場データ分析',
          '翌年度へのデータ引き継ぎ',
          '多言語対応',
        ],
      },
      {
        id: 'usage_interest',
        label:
          '文化祭専用サイトが簡単に作れる場合、自分の学校で使ってみたいですか',
        kind: 'single',
        required: true,
        options: [
          'ぜひ使いたい',
          '条件が合えば使いたい',
          '詳しい内容を知りたい',
          'あまり必要ない',
          '分からない',
        ],
      },
    ],
  },
  {
    id: 'trial',
    title: '試験導入について',
    description: '最後に、試験導入やご意見について教えてください。',
    questions: [
      {
        id: 'trial_interest',
        label: 'Festival Naviの無料デモや試験導入に興味がありますか',
        kind: 'single',
        required: true,
        options: [
          '無料試験導入に興味がある',
          'デモを見てみたい',
          '詳しい説明を聞きたい',
          '今回はアンケートのみ',
        ],
      },
      // ↓ trial_interest が上位3つのときのみ表示される連絡先（任意）
      {
        id: 'contact_name',
        label: '名前または担当者名（任意）',
        kind: 'text',
        required: false,
        maxLength: 40,
        placeholder: '例）文化祭実行委員 山田',
      },
      {
        id: 'contact_email',
        label: 'メールアドレス（任意）',
        kind: 'text',
        required: false,
        maxLength: 120,
        placeholder: '例）example@school.ac.jp',
      },
      {
        id: 'contact_method',
        label: 'SNSまたはその他の連絡方法（任意）',
        kind: 'text',
        required: false,
        maxLength: 120,
        placeholder: '例）InstagramのDM / 学校代表メール など',
      },
      {
        id: 'festival_schedule',
        label: '文化祭の開催予定時期（任意）',
        kind: 'text',
        required: false,
        maxLength: 60,
        placeholder: '例）2026年9月ごろ',
      },
      {
        id: 'consultation_details',
        label: '相談したい内容（任意）',
        kind: 'textarea',
        required: false,
        maxLength: 500,
        placeholder: '例）来場者向けのマップと混雑表示を試したいです。',
      },
      // ↑ ここまで条件付き
      {
        id: 'additional_feedback',
        label: 'Festival Naviへの意見や要望（任意）',
        kind: 'textarea',
        required: false,
        maxLength: 500,
        placeholder: 'ご自由にお書きください。',
      },
      {
        id: 'statistics_consent',
        label:
          '調査結果を匿名の統計情報として、発表資料やサービス改善に利用することに同意します',
        note: '個人が特定できる情報は、本人の許可なく公開しません。（同意が必須です）',
        kind: 'consent',
        required: true,
      },
    ],
  },
]

/** 連絡先フィールドのidリスト（条件表示の判定に使用） */
export const CONTACT_FIELD_IDS: (keyof SurveyAnswers)[] = [
  'contact_name',
  'contact_email',
  'contact_method',
  'festival_schedule',
  'consultation_details',
]

/** 空の回答の初期値 */
export const EMPTY_ANSWERS: SurveyAnswers = {
  respondent_role: '',
  prefecture: '',
  school_type: '',
  school_name: '',
  current_information_methods: [],
  update_availability: '',
  emergency_communication_methods: [],
  congestion_experience: '',
  operational_problems: [],
  biggest_problem: '',
  problem_details: '',
  desired_features: [],
  most_desired_feature: '',
  usage_interest: '',
  trial_interest: '',
  contact_name: '',
  contact_email: '',
  contact_method: '',
  festival_schedule: '',
  consultation_details: '',
  additional_feedback: '',
  statistics_consent: false,
}
